### ISSUE TITLE
Re-build documentation to include recent additions

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#146]
The [project documentation](apiumbrella.io/docs/) has not been updated to include recent pull requests. Please re-generate the documentation to include recent changes, including:

* [ ] [Admin REST API](https://github.com/NREL/api-umbrella/pull/142)
* [ ] [API Scopes](https://github.com/NREL/api-umbrella/pull/136) (Issue #130)
* [ ] [Deployment diagram](https://github.com/NREL/api-umbrella/pull/110)
* [ ] [Administration guide](https://github.com/NREL/api-umbrella/pull/73)

Additional documentation topics
---
* [ ] [HTTP Accept headers](https://github.com/NREL/api-umbrella/issues/145)
* [ ] [Programmatic access to analytics data](https://github.com/NREL/api-umbrella/issues/140)
* [ ] [API User Mailer configuration options](https://github.com/NREL/api-umbrella/issues/138)
* [ ] [Multi-node deployment](https://github.com/NREL/api-umbrella/issues/125)

**Comment by brylie** [comment]
@darylrobbins are there any other documentation tasks that can be added to this list?

**Comment by brylie** [comment]
It is worth noting that the Github wiki also contains documentation. The Wiki is easier to edit, and more participatory. What would you all think about using the Github wiki section as the primary API Umbrella documentation? 

@GUI @NRELAdmin @darylrobbins @dwcaraway

**Comment by dwcaraway** [comment]
sounds fine to me but not involved with the project, defer to @GUI

**Comment by GUI** [comment]
I've shifted the documentation to use ReadTheDocs and updated various pieces: https://api-umbrella.readthedocs.org/en/latest/ So I'm going to close this, but let me know if I missed anything. We could of course always use more documentation, but I think we'd like to shift towards using ReadTheDocs, if that sounds good (it does lots of nice things for creating more organized docs).
