### ISSUE TITLE
Choose dates for travel to Mindtrek Openmind conference

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#161]
@GUI ,
Please choose your dates for travel to Finland to attend the [Mindtrek Openmind](https://www.mindtrek.org/2015/) conference.

## Task
* [ ] Decide how long you wish to stay in Finland
* [ ] Choose a timespan that includes the Mindtrek Openmind event (September 22-24th 2015)
* [ ] Respond to this issue with specific dates (with a +/- 3 day flexibility if possible)

**Comment by GUI** [comment]
Thanks!
